[project]
name = "omnibus-verification-engine"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/workspace/omnibus-verification-engine/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.omnibus-verification-engine]
path = "contracts/omnibus-verification-engine.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
